declare module 'swiper/css';
declare module 'swiper/css/navigation';
declare module 'swiper/css/pagination';
declare module 'swiper/css/free-mode';
declare module 'swiper/css/autoplay';
declare module "swiper/react";
declare module "swiper/modules";
declare module 'swiper/css/grid';
declare module 'flowbite-react';